enableGlobalCache: true

packageExtensions:
  eslint-plugin-canonical@*:
    dependencies:
      "@typescript-eslint/types": "*"
      array-includes: "*"
      doctrine: "*"
      tsconfig-paths: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
