compressionLevel: mixed

enableGlobalCache: true

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  eslint-plugin-canonical@*:
    dependencies:
      "@typescript-eslint/types": "*"
      array-includes: "*"
      doctrine: "*"
      tsconfig-paths: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
